#include <stdint.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include <Arduino.h>

#include "config.h"
#include "touch_sound.h"
#include "synth.h"
#include "sinetable.h"
#include "audio.h"

// Variable to hold the next note that will be generated by the synth 
static volatile uint8_t next_note;
// Variable to hold the next sample that will be output to the speaker
static volatile uint8_t next_sample;

// Flag indicating whether the next sample has been computed.
static volatile uint8_t synth_ready;

// Flag indicating whether or not the synth is active
static volatile uint8_t synth_active;

// Schedule the synth
void synth_init(void) {

    PORTF = (1 << LED1);
    TCCR3A = (1 << WGM31) | (1 << WGM30);
    TCCR3B = (1 << WGM33) |  (1 << CS30);
    TIMSK3 = 1 << OCIE3A;
    OCR3A = 0x022C; // N = 14400

    synth_ready = 1;
}

void synth_enable(void) {
    synth_active = 0;
}

void synth_disable(void) {
    synth_active = 1;

}

static volatile uint8_t t_inc = 1;
static volatile uint8_t t_pos = 0;
volatile static uint16_t last_note;

static volatile uint16_t carrier_inc;
static volatile uint16_t carrier_pos = 0;
static volatile uint16_t modulator_inc;
static volatile uint16_t modulator_pos = 0;
static volatile uint8_t amplitude = 60;

static volatile uint16_t mod_ratio_numerator = 0;
static volatile uint16_t mod_ratio_denominator = 1; 

void synth_clear() {
    carrier_pos = 0;
    modulator_pos = 0;
}

void synth_set_mod_ratio(uint16_t mod_ratio_numerator_v, uint16_t mod_ratio_denominator_v) {
    mod_ratio_numerator = mod_ratio_numerator_v;
    mod_ratio_denominator = mod_ratio_denominator_v;
}

void play_note(uint16_t note) {
    next_note = note;
}

void synth_generate(uint16_t note) {

    uint8_t cpos;
    uint8_t mpos;

    uint8_t modulation;

    if(synth_ready) return;
    PORTF |= (1 << LED2); 

    carrier_inc = note;

    modulator_inc = carrier_inc * mod_ratio_numerator / mod_ratio_denominator;

    cpos = 0;
    mpos = 0;

    modulator_pos += modulator_inc;
    mpos = modulator_pos & SINETABLE_MASK;
    modulation = pgm_read_byte(&sinetable[mpos]);

    carrier_pos += carrier_inc; // should this effect the frequency?
    cpos = (carrier_pos + modulation) & SINETABLE_MASK;

    next_sample = (pgm_read_byte(&sinetable[cpos]) * amplitude) >> 3;

    last_note = note;
    synth_ready = 1;
}

ISR(TIMER3_COMPA_vect) {
    if(synth_active) return;
    synth_generate(next_note);
    audio_output(next_sample);
    synth_ready = 0;

}
